[package]
name = "mambretti"
version = "2.0.0"
authors = ["Andrea Mambretti <mbr@ccs.neu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qt_widgets="0.4.1"
